# Site settings
course_name: "AI for SME Success: Strategic Implementation & Business Growth"
course_description: "A comprehensive course for SME owners and managers on implementing AI solutions to drive business growth."
course_semester: "2025"

# URLs
baseurl: "/ai-course-business"
url: "https://insopt2012.github.io"

# Theme settings
theme_skin: blue # blue, green, orange, purple, turquoise, red
navbar_color: "navbar-dark" # navbar-light (light background with dark text)  or navbar-dark (dark background with light text)

# Author/Organization info
schoolname: "AI for SME Success"
schoolurl: "https://insopt2012.github.io/ai-course-business"
twitter_username: # your-twitter-handle (optional, remove if not using) 

address: |
    AI for SME Success
    Online Course
    2025

# Set your Google Analytics tracking ID (optional)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
